# Generated by Django 5.0.2 on 2024-03-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_rename_statuses_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
